---
name: ci

on:
  pull_request:
    branches: [main]

jobs:
  styles:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Style
        run: (test -z $(go fmt ./...))
      - name: Install staticccheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: StaticCheck
        run: (staticcheck ./...)

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Run tests...
        run: (go test ./... -cover)
